- hosts: all
  tasks:
    - debug: msg="We're currently in the {{ ansible_local.environment }} env"
    - debug: msg="This node has certname {{ ansible_local.id }}"
    - debug: msg="Thus, we must use port {{ lookup('jerakia', 'httpd/port') }}!"

